import { useEffect, useState } from 'react';
import { apiFetch, isAndroidMode } from '../auth';
import type { Lang } from '../i18n/translations';

type Props={lang:Lang}; type AnyRow=Record<string,any>;
async function jsonReq(path:string,opts?:RequestInit){const r=await apiFetch(path,opts);if(!r.ok)throw new Error(await r.text());return r.json()}
function responseFilename(r:Response,type:string){const explicit=r.headers.get('X-PMPoshan-Filename');if(explicit)return explicit;const cd=r.headers.get('Content-Disposition')||'';const m=cd.match(/filename="?([^";]+)"?/i);if(m?.[1])return m[1];return r.headers.get('Content-Type')?.includes('application/vnd.ms-excel')?`PM_POSHAN_${type}.xls`:`PM_POSHAN_${type}.xlsx`;}
export default function CustomReports({lang}:Props){const mr=lang==='mr'; const [defs,setDefs]=useState<AnyRow[]>([]),[type,setType]=useState('DAILY_MEALS'),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<AnyRow|null>(null),[err,setErr]=useState(''); const [districts,setDistricts]=useState<AnyRow[]>([]),[schools,setSchools]=useState<AnyRow[]>([]); const [f,setF]=useState<AnyRow>({date_from:new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10),date_to:new Date().toISOString().slice(0,10),year:new Date().getFullYear(),month:new Date().getMonth()+1,district_id:'',school_id:''});
  useEffect(()=>{Promise.all([jsonReq('/custom-reports/definitions'),jsonReq('/districts'),jsonReq('/schools')]).then(([d,di,s])=>{setDefs(d);setDistricts(di);setSchools(s);const x=d.find((z:any)=>z.report_type==='DAILY_MEALS')||d[0];if(x){setType(x.report_type);setSelected(x.columns.map((c:any)=>c.key))}}).catch(e=>setErr(String(e)))},[]);
  const def=defs.find(x=>x.report_type===type); const changeType=(v:string)=>{setType(v);const d=defs.find(x=>x.report_type===v);setSelected(d?.columns.map((c:any)=>c.key)||[]);setPreview(null)};
  const payload=()=>({report_type:type,language:lang,columns:selected,district_id:f.district_id||null,school_id:f.school_id||null,date_from:f.date_from||null,date_to:f.date_to||null,year:Number(f.year)||null,month:Number(f.month)||null,max_preview_rows:100});
  const runPreview=async()=>{try{setErr('');setPreview(await jsonReq('/custom-reports/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())}))}catch(e){setErr(String(e))}};
  const download=async()=>{try{setErr('');const r=await apiFetch('/custom-reports/excel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload())});if(!r.ok)throw new Error(await r.text());const blob=await r.blob();const filename=responseFilename(r,type);const file=new File([blob],filename,{type:blob.type||'application/octet-stream'});const nav:any=navigator;if(isAndroidMode()&&nav.share&&(!nav.canShare||nav.canShare({files:[file]}))){await nav.share({files:[file],title:filename});return;}const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setErr(String(e))}};
  return <main className="content"><section className="panel"><h2>{mr?'सानुकूल Excel अहवाल':'Custom Excel Reports'}</h2><p>{mr?'अहवाल प्रकार, कालावधी, शाळा व आवश्यक स्तंभ निवडा.':'Choose report type, period, school and exactly the columns you need.'}</p>{err&&<div className="api-error">{err}</div>}
    <div className="filters"><label>{mr?'अहवाल प्रकार':'Report Type'}<select value={type} onChange={e=>changeType(e.target.value)}>{defs.map(d=><option key={d.report_type} value={d.report_type}>{mr?d.title_mr:d.title_en}</option>)}</select></label><label>{mr?'जिल्हा':'District'}<select value={f.district_id} onChange={e=>setF({...f,district_id:e.target.value})}><option value="">{mr?'सर्व':'All'}</option>{districts.map(x=><option key={x.id} value={x.id}>{mr?x.name_mr:x.name_en}</option>)}</select></label><label>{mr?'शाळा':'School'}<select value={f.school_id} onChange={e=>setF({...f,school_id:e.target.value})}><option value="">{mr?'सर्व उपलब्ध':'All accessible'}</option>{schools.map(x=><option key={x.id} value={x.id}>{mr?x.name_mr:x.name_en}</option>)}</select></label></div>
    {(type==='DAILY_MEALS'||type==='STOCK_LEDGER')&&<div className="filters"><label>{mr?'पासून':'From'}<input type="date" value={f.date_from} onChange={e=>setF({...f,date_from:e.target.value})}/></label><label>{mr?'पर्यंत':'To'}<input type="date" value={f.date_to} onChange={e=>setF({...f,date_to:e.target.value})}/></label></div>}
    {type==='MONTHLY_RETURNS'&&<div className="filters"><label>{mr?'वर्ष':'Year'}<input type="number" value={f.year} onChange={e=>setF({...f,year:e.target.value})}/></label><label>{mr?'महिना':'Month'}<input type="number" min="1" max="12" value={f.month} onChange={e=>setF({...f,month:e.target.value})}/></label></div>}
    <h3>{mr?'Excel मध्ये घ्यायचे स्तंभ':'Columns to include in Excel'}</h3><div className="column-picker">{def?.columns.map((c:any)=><label key={c.key} className="checkline"><input type="checkbox" checked={selected.includes(c.key)} onChange={e=>setSelected(e.target.checked?[...selected,c.key]:selected.filter(x=>x!==c.key))}/>{mr?c.label_mr:c.label_en}</label>)}</div><div className="actions"><button onClick={()=>setSelected(def?.columns.map((c:any)=>c.key)||[])}>{mr?'सर्व निवडा':'Select All'}</button><button onClick={runPreview}>{mr?'पूर्वदृश्य':'Preview'}</button><button onClick={download}>⬇ Excel</button></div>
  </section>{preview&&<section className="panel"><h3>{mr?'पूर्वदृश्य':'Preview'} — {preview.total_rows} {mr?'नोंदी':'rows'}</h3><div className="table-scroll"><table><thead><tr>{preview.columns.map((c:any)=><th key={c.key}>{c.label}</th>)}</tr></thead><tbody>{preview.rows.map((r:any,i:number)=><tr key={i}>{preview.columns.map((c:any)=><td key={c.key}>{String(r[c.key]??'')}</td>)}</tr>)}</tbody></table></div></section>}</main>}