import { useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../auth';
import type { Lang } from '../i18n/translations';

type Props={lang:Lang};
type AnyRow=Record<string,any>;
const today=()=>new Date().toISOString().slice(0,10);

async function jsonReq(path:string, opts?:RequestInit){const r=await apiFetch(path,opts); if(!r.ok) throw new Error(await r.text()); return r.json();}

export default function MasterData({lang}:Props){
  const mr=lang==='mr'; const [tab,setTab]=useState('districts'); const [msg,setMsg]=useState(''); const [err,setErr]=useState('');
  const [districts,setDistricts]=useState<AnyRow[]>([]),[blocks,setBlocks]=useState<AnyRow[]>([]),[clusters,setClusters]=useState<AnyRow[]>([]),[schools,setSchools]=useState<AnyRow[]>([]),[ingredients,setIngredients]=useState<AnyRow[]>([]),[menus,setMenus]=useState<AnyRow[]>([]);
  const [edit,setEdit]=useState<AnyRow|null>(null); const [recipeMenu,setRecipeMenu]=useState(''); const [recipeDate,setRecipeDate]=useState(today()); const [recipeItems,setRecipeItems]=useState<AnyRow[]>([]);
  const reload=async()=>{try{setErr(''); const [d,b,c,s,i,m]=await Promise.all(['/master/districts','/master/blocks','/master/clusters','/master/schools','/master/ingredients','/master/menus'].map(x=>jsonReq(x))); setDistricts(d);setBlocks(b);setClusters(c);setSchools(s);setIngredients(i);setMenus(m); if(!recipeMenu&&m[0])setRecipeMenu(m[0].id);}catch(e){setErr(String(e))}};
  useEffect(()=>{reload()},[]);
  useEffect(()=>{if(recipeMenu) loadRecipe()},[recipeMenu,recipeDate]);
  const loadRecipe=async()=>{try{const d=await jsonReq(`/master/menus/${recipeMenu}/recipe-standard?on_date=${recipeDate}`);setRecipeItems(d.items||[])}catch(e){setErr(String(e))}};
  const save=(kind:string,payload:AnyRow)=>async()=>{try{setErr('');setMsg('');const path=`/master/${kind}${edit?.id?`/${edit.id}`:''}`;await jsonReq(path,{method:edit?.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});setEdit(null);setMsg(mr?'जतन केले':'Saved');await reload()}catch(e){setErr(String(e))}};
  const input=(key:string,label:string,type='text')=><label>{label}<input type={type} value={edit?.[key]??''} onChange={e=>setEdit({...edit,[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>;
  const check=(key:string,label:string)=><label className="checkline"><input type="checkbox" checked={edit?.[key]??true} onChange={e=>setEdit({...edit,[key]:e.target.checked})}/>{label}</label>;
  const rows=tab==='districts'?districts:tab==='blocks'?blocks:tab==='clusters'?clusters:tab==='schools'?schools:tab==='ingredients'?ingredients:menus;
  const newRow=()=>{const base:any={active:true}; if(tab==='blocks')base.district_id=districts[0]?.id||''; if(tab==='clusters')base.block_id=blocks[0]?.id||''; if(tab==='schools'){base.cluster_id=clusters[0]?.id||'';base.class_1_5_strength=0;base.class_6_8_strength=0} if(tab==='ingredients'){Object.assign(base,{category:'CONSUMABLE',base_unit:'KG',reorder_level:0,safety_stock:0,track_inventory:true})} if(tab==='menus'){Object.assign(base,{week_pattern:'CUSTOM',day_of_week:1})} setEdit(base)};
  const form=()=>{if(!edit)return null; if(tab==='districts')return <div className="master-form">{input('code',mr?'कोड':'Code')}{input('name_en','Name English')}{input('name_mr','नाव मराठी')}{check('active',mr?'सक्रिय':'Active')}<button onClick={save('districts',edit)}>{mr?'जतन':'Save'}</button></div>;
    if(tab==='blocks')return <div className="master-form">{input('code',mr?'तालुका कोड':'Taluka Code')}<label>{mr?'जिल्हा':'District'}<select value={edit.district_id||''} onChange={e=>setEdit({...edit,district_id:e.target.value})}>{districts.map(x=><option value={x.id}>{mr?x.name_mr:x.name_en}</option>)}</select></label>{input('name_en','Name English')}{input('name_mr','नाव मराठी')}{check('active',mr?'सक्रिय':'Active')}<button onClick={save('blocks',edit)}>Save</button></div>;
    if(tab==='clusters')return <div className="master-form">{input('code',mr?'केंद्र कोड':'Cluster Code')}<label>{mr?'तालुका':'Taluka'}<select value={edit.block_id||''} onChange={e=>setEdit({...edit,block_id:e.target.value})}>{blocks.map(x=><option value={x.id}>{mr?x.name_mr:x.name_en}</option>)}</select></label>{input('name_en','Name English')}{input('name_mr','नाव मराठी')}{check('active',mr?'सक्रिय':'Active')}<button onClick={save('clusters',edit)}>Save</button></div>;
    if(tab==='schools')return <div className="master-form">{input('code',mr?'शाळा कोड':'School Code')}{input('udise_code','UDISE Code')}<label>{mr?'केंद्र':'Cluster'}<select value={edit.cluster_id||''} onChange={e=>setEdit({...edit,cluster_id:e.target.value})}>{clusters.map(x=><option value={x.id}>{mr?x.name_mr:x.name_en}</option>)}</select></label>{input('name_en','Name English')}{input('name_mr','नाव मराठी')}{input('village',mr?'गाव':'Village')}{input('class_1_5_strength',mr?'इ.1-5 पटसंख्या':'Class 1-5 Strength','number')}{input('class_6_8_strength',mr?'इ.6-8 पटसंख्या':'Class 6-8 Strength','number')}{check('active',mr?'सक्रिय':'Active')}<button onClick={save('schools',edit)}>Save</button></div>;
    if(tab==='ingredients')return <div className="master-form">{input('code',mr?'साहित्य कोड':'Ingredient Code')}{input('name_en','Name English')}{input('name_mr','नाव मराठी')}{input('category',mr?'प्रकार':'Category')}<label>{mr?'एकक':'Unit'}<select value={edit.base_unit||'KG'} onChange={e=>setEdit({...edit,base_unit:e.target.value})}>{['KG','G','L','ML','EA','INR'].map(x=><option>{x}</option>)}</select></label>{input('reorder_level',mr?'पुनर्मागणी पातळी':'Reorder Level','number')}{input('safety_stock',mr?'सुरक्षित साठा':'Safety Stock','number')}{check('track_inventory',mr?'साठा ट्रॅक करा':'Track Inventory')}{check('active',mr?'सक्रिय':'Active')}<button onClick={save('ingredients',edit)}>Save</button></div>;
    return <div className="master-form">{input('code',mr?'मेनू कोड':'Menu Code')}{input('name_en','Name English')}{input('name_mr','नाव मराठी')}{input('week_pattern',mr?'आठवडा नमुना':'Week Pattern')}<label>{mr?'वार':'Day'}<select value={edit.day_of_week||1} onChange={e=>setEdit({...edit,day_of_week:Number(e.target.value)})}>{[1,2,3,4,5,6].map(x=><option value={x}>{x}</option>)}</select></label>{check('active',mr?'सक्रिय':'Active')}<button onClick={save('menus',edit)}>Save</button></div>};
  const headers=useMemo(()=>tab==='schools'?['code','udise_code','name_en','name_mr','village']:tab==='ingredients'?['code','name_en','name_mr','base_unit','reorder_level']:tab==='menus'?['code','name_en','name_mr','week_pattern','day_of_week']:['code','name_en','name_mr'],[tab]);
  const saveRecipe=async()=>{try{await jsonReq(`/master/menus/${recipeMenu}/recipe-standard`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({effective_from:recipeDate,items:recipeItems.map(x=>({ingredient_id:x.ingredient_id,qty_class_1_5:Number(x.qty_class_1_5)||0,qty_class_6_8:Number(x.qty_class_6_8)||0,unit:x.unit}))})});setMsg(mr?'प्रमाणित मात्रा जतन केली':'Standard quantities saved');await loadRecipe()}catch(e){setErr(String(e))}};
  return <main className="content"><section className="panel"><h2>{mr?'मास्टर डेटा व्यवस्थापन':'Master Data Management'}</h2><p>{mr?'नवीन जिल्हा, तालुका, केंद्र, शाळा, साहित्य व मेनू तयार/संपादित करा.':'Add or edit districts, talukas, clusters, schools, ingredients and menus.'}</p>{err&&<div className="api-error">{err}</div>}{msg&&<div className="success-box">{msg}</div>}
    <div className="master-tabs">{[['districts','District / जिल्हा'],['blocks','Taluka / तालुका'],['clusters','Cluster / केंद्र'],['schools','School / शाळा'],['ingredients','Ingredients / साहित्य'],['menus','Menu / मेनू']].map(([k,l])=><button className={tab===k?'active':''} onClick={()=>{setTab(k);setEdit(null)}}>{l}</button>)}</div>
    <button onClick={newRow}>＋ {mr?'नवीन नोंद':'Add New'}</button>{form()}
    <div className="table-scroll"><table><thead><tr>{headers.map(h=><th>{h}</th>)}<th>{mr?'सक्रिय':'Active'}</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{headers.map(h=><td>{String(r[h]??'')}</td>)}<td>{r.active?'✓':'—'}</td><td><button onClick={()=>setEdit({...r})}>{mr?'संपादित':'Edit'}</button></td></tr>)}</tbody></table></div>
  </section>
  {tab==='menus'&&<section className="panel"><h2>{mr?'मेनू साहित्य व प्रमाणित प्रति विद्यार्थी मात्रा':'Menu Ingredients & Standard Per-Student Quantity'}</h2><div className="filters"><label>{mr?'मेनू':'Menu'}<select value={recipeMenu} onChange={e=>setRecipeMenu(e.target.value)}>{menus.filter(x=>x.active).map(x=><option value={x.id}>{mr?x.name_mr:x.name_en}</option>)}</select></label><label>{mr?'लागू दिनांक':'Effective Date'}<input type="date" value={recipeDate} onChange={e=>setRecipeDate(e.target.value)}/></label></div>
    <div className="table-scroll"><table><thead><tr><th>{mr?'साहित्य':'Ingredient'}</th><th>{mr?'इ.1-5 प्रति विद्यार्थी':'Class 1-5 / student'}</th><th>{mr?'इ.6-8 प्रति विद्यार्थी':'Class 6-8 / student'}</th><th>{mr?'एकक':'Unit'}</th></tr></thead><tbody>{recipeItems.map((x,i)=><tr key={x.ingredient_id}><td>{mr?x.name_mr:x.name_en} ({x.code})</td><td><input type="number" step="0.000001" min="0" value={x.qty_class_1_5} onChange={e=>setRecipeItems(recipeItems.map((z,j)=>j===i?{...z,qty_class_1_5:e.target.value}:z))}/></td><td><input type="number" step="0.000001" min="0" value={x.qty_class_6_8} onChange={e=>setRecipeItems(recipeItems.map((z,j)=>j===i?{...z,qty_class_6_8:e.target.value}:z))}/></td><td><select value={x.unit} onChange={e=>setRecipeItems(recipeItems.map((z,j)=>j===i?{...z,unit:e.target.value}:z))}>{['KG','G','L','ML','EA','INR'].map(u=><option>{u}</option>)}</select></td></tr>)}</tbody></table></div><button onClick={saveRecipe}>{mr?'प्रमाणित मात्रा जतन करा':'Save Standard Quantities'}</button>
  </section>}</main>
}
