import { useEffect, useMemo, useState } from 'react';
import { apiFetch } from '../auth';
import type { Lang } from '../i18n/translations';

type Props={lang:Lang};
type School={id:string;name_en:string;name_mr:string;udise_code:string};
type UserRow={id:string;username:string;display_name?:string;role:string;active:boolean;school_ids:string[];school_access?:{school_id:string;name_en:string;name_mr:string}[];last_login_at?:string|null};
type DeviceInfo={installation_id:string;app_version:string;schema_version:number;data_dir:string;license:any};
type Tab='users'|'device'|'masters';

async function jsonReq(path:string,opts?:RequestInit){const r=await apiFetch(path,opts);const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.detail||JSON.stringify(body)||`HTTP ${r.status}`);return body;}

export default function SystemAdministration({lang}:Props){
 const mr=lang==='mr';
 const [tab,setTab]=useState<Tab>('users');
 const [users,setUsers]=useState<UserRow[]>([]);const [schools,setSchools]=useState<School[]>([]);const [device,setDevice]=useState<DeviceInfo|null>(null);
 const [msg,setMsg]=useState('');const [err,setErr]=useState('');const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({username:'',display_name:'',password:'',role:'HEADMASTER',school_ids:[] as string[],preferred_language:'mr'});
 const [edit,setEdit]=useState<UserRow|null>(null);const [resetFor,setResetFor]=useState<UserRow|null>(null);const [resetPassword,setResetPassword]=useState('');

 const reload=async()=>{try{setErr('');const [u,s,d]=await Promise.all([jsonReq('/admin/users'),jsonReq('/schools'),jsonReq('/admin/device')]);setUsers(u);setSchools(s);setDevice(d);}catch(e){setErr(String(e))}};
 useEffect(()=>{reload()},[]);
 const roleLabel=(r:string)=>r==='SYSTEM_ADMIN'?(mr?'सिस्टम प्रशासक':'System Admin'):r==='HEADMASTER'?(mr?'मुख्याध्यापक':'Headmaster'):(mr?'शिक्षक':'Teacher');
 const schoolMap=useMemo(()=>Object.fromEntries(schools.map(s=>[s.id,s])),[schools]);
 const toggleSchool=(id:string,current:string[],set:(v:string[])=>void)=>set(current.includes(id)?current.filter(x=>x!==id):[...current,id]);
 const clearMessages=()=>{setErr('');setMsg('')};

 const createUser=async()=>{try{clearMessages();setBusy(true);await jsonReq('/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setForm({username:'',display_name:'',password:'',role:'HEADMASTER',school_ids:[],preferred_language:'mr'});setMsg(mr?'वापरकर्ता तयार केला':'User account created');await reload();}catch(e){setErr(String(e))}finally{setBusy(false)}};
 const saveEdit=async()=>{if(!edit)return;try{clearMessages();setBusy(true);await jsonReq(`/admin/users/${edit.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({display_name:edit.display_name||'',role:edit.role,active:edit.active,school_ids:edit.school_ids})});setEdit(null);setMsg(mr?'वापरकर्ता अद्ययावत केला':'User updated');await reload();}catch(e){setErr(String(e))}finally{setBusy(false)}};
 const toggleActive=async(u:UserRow)=>{try{clearMessages();setBusy(true);await jsonReq(`/admin/users/${u.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({active:!u.active})});setMsg(mr?'स्थिती बदलली':'Account status updated');await reload();}catch(e){setErr(String(e))}finally{setBusy(false)}};
 const doReset=async()=>{if(!resetFor)return;try{clearMessages();setBusy(true);await jsonReq(`/admin/users/${resetFor.id}/reset-password`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:resetPassword})});setResetFor(null);setResetPassword('');setMsg(mr?'पासवर्ड रीसेट केला':'Password reset');}catch(e){setErr(String(e))}finally{setBusy(false)}};
 const restoreMasters=async()=>{if(!confirm(mr?'मानक साहित्य व मेनू यादी पुनर्संचयित करायची? विद्यमान कोड हटवले जाणार नाहीत.':'Restore the standard ingredient and menu lists? Existing coded rows will not be deleted.'))return;try{clearMessages();setBusy(true);const r=await jsonReq('/admin/restore-standard-masters',{method:'POST'});setMsg(mr?`पुनर्संचयित पूर्ण: साहित्य ${r.ingredients_total}, मेनू ${r.menus_total}`:`Restore complete: ${r.ingredients_total} ingredients and ${r.menus_total} menus available`);}catch(e){setErr(String(e))}finally{setBusy(false)}};
 const copyActivationRequest=async()=>{if(!device)return;const request={product:'PM_POSHAN',request_type:'DEVICE_ACTIVATION',installation_id:device.installation_id,app_version:device.app_version,current_license:device.license?.license?.license_id||null,udise:device.license?.license?.udise||schools[0]?.udise_code||null};await navigator.clipboard.writeText(JSON.stringify(request,null,2));setMsg(mr?'डिव्हाइस विनंती कॉपी केली':'Device authorization request copied');};

 const userForm=(editing:boolean)=>{const data:any=editing?edit:form;if(!data)return null;const setData=(next:any)=>editing?setEdit(next):setForm(next);return <div className="master-form">
   {!editing&&<label>{mr?'यूजर आयडी':'User ID'}<input value={data.username} onChange={e=>setData({...data,username:e.target.value})}/></label>}
   <label>{mr?'नाव':'Display Name'}<input value={data.display_name||''} onChange={e=>setData({...data,display_name:e.target.value})}/></label>
   {!editing&&<label>{mr?'तात्पुरता पासवर्ड':'Initial Password'}<input type="password" value={data.password} onChange={e=>setData({...data,password:e.target.value})} placeholder={mr?'किमान 10 अक्षरे':'Minimum 10 characters'}/></label>}
   <label>{mr?'भूमिका':'Role'}<select value={data.role} onChange={e=>setData({...data,role:e.target.value})}><option value="HEADMASTER">Headmaster / मुख्याध्यापक</option><option value="TEACHER">Teacher / शिक्षक</option><option value="SYSTEM_ADMIN">System Admin / सिस्टम प्रशासक</option></select></label>
   {editing&&<label className="checkline"><input type="checkbox" checked={!!data.active} onChange={e=>setData({...data,active:e.target.checked})}/>{mr?'खाते सक्रिय':'Account active'}</label>}
   {data.role!=='SYSTEM_ADMIN'&&<div style={{gridColumn:'1 / -1'}}><b>{mr?'शाळा प्रवेश':'School access'}</b><div className="check-grid">{schools.map(s=><label className="checkline" key={s.id}><input type="checkbox" checked={(data.school_ids||[]).includes(s.id)} onChange={()=>toggleSchool(s.id,data.school_ids||[],v=>setData({...data,school_ids:v}))}/>{mr?s.name_mr:s.name_en} ({s.udise_code})</label>)}</div></div>}
   <button disabled={busy} onClick={editing?saveEdit:createUser}>{editing?(mr?'बदल जतन करा':'Save changes'):(mr?'वापरकर्ता तयार करा':'Create user')}</button>{editing&&<button className="secondary" onClick={()=>setEdit(null)}>{mr?'रद्द':'Cancel'}</button>}
  </div>};

 return <main className="content"><section className="panel"><h2>{mr?'सिस्टम प्रशासन':'System Administration'}</h2><p>{mr?'वापरकर्ता खाती, डिव्हाइस परवाना आणि मानक मास्टर डेटा नियंत्रित करा.':'Manage local user accounts, device licensing information and standard master recovery.'}</p>{err&&<div className="api-error">{err}</div>}{msg&&<div className="success-box">{msg}</div>}
  <div className="master-tabs"><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}>{mr?'वापरकर्ता खाती':'User Accounts'}</button><button className={tab==='device'?'active':''} onClick={()=>setTab('device')}>{mr?'डिव्हाइस व परवाना':'Device & License'}</button><button className={tab==='masters'?'active':''} onClick={()=>setTab('masters')}>{mr?'मास्टर पुनर्प्राप्ती':'Master Recovery'}</button></div>
 </section>

 {tab==='users'&&<><section className="panel"><h3>{mr?'नवीन खाते तयार करा':'Create Headmaster / Teacher / Admin Account'}</h3>{userForm(false)}</section><section className="panel"><h3>{mr?'वापरकर्ता यादी':'User Accounts'}</h3><div className="table-scroll"><table><thead><tr><th>{mr?'यूजर आयडी':'User ID'}</th><th>{mr?'नाव':'Name'}</th><th>{mr?'भूमिका':'Role'}</th><th>{mr?'शाळा':'School'}</th><th>{mr?'स्थिती':'Status'}</th><th>{mr?'शेवटचा लॉगिन':'Last Login'}</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.username}</b></td><td>{u.display_name||'—'}</td><td>{roleLabel(u.role)}</td><td>{u.role==='SYSTEM_ADMIN'?(mr?'सर्व शाळा':'All schools'):(u.school_ids||[]).map(id=>mr?schoolMap[id]?.name_mr:schoolMap[id]?.name_en).filter(Boolean).join(', ')||'—'}</td><td>{u.active?(mr?'सक्रिय':'Active'):(mr?'बंद':'Disabled')}</td><td>{u.last_login_at?new Date(u.last_login_at).toLocaleString():'—'}</td><td><button onClick={()=>setEdit({...u,school_ids:[...(u.school_ids||[])]})}>{mr?'संपादित':'Edit'}</button> <button onClick={()=>{setResetFor(u);setResetPassword('')}}>{mr?'पासवर्ड':'Password'}</button> <button onClick={()=>toggleActive(u)}>{u.active?(mr?'बंद करा':'Disable'):(mr?'सक्रिय करा':'Enable')}</button></td></tr>)}</tbody></table></div></section>{edit&&<section className="panel"><h3>{mr?'वापरकर्ता संपादित करा':'Edit User'}</h3>{userForm(true)}</section>}{resetFor&&<section className="panel"><h3>{mr?'पासवर्ड रीसेट':'Reset Password'} — {resetFor.username}</h3><div className="master-form"><label>{mr?'नवीन पासवर्ड':'New password'}<input type="password" value={resetPassword} onChange={e=>setResetPassword(e.target.value)} placeholder={mr?'किमान 10 अक्षरे':'Minimum 10 characters'}/></label><button disabled={busy} onClick={doReset}>{mr?'पासवर्ड बदला':'Reset password'}</button><button className="secondary" onClick={()=>setResetFor(null)}>{mr?'रद्द':'Cancel'}</button></div></section>}</>}

 {tab==='device'&&<section className="panel"><h3>{mr?'डिव्हाइस माहिती':'Device Authorization'}</h3>{device?<div className="summary-grid"><div><small>Installation ID</small><strong style={{wordBreak:'break-all'}}>{device.installation_id}</strong></div><div><small>{mr?'अॅप आवृत्ती':'App Version'}</small><strong>{device.app_version}</strong></div><div><small>{mr?'परवाना':'License'}</small><strong>{device.license?.active?'ACTIVE':'INACTIVE'} — {device.license?.reason}</strong></div><div><small>{mr?'परवाना आयडी':'License ID'}</small><strong>{device.license?.license?.license_id||'—'}</strong></div><div><small>{mr?'वैध पर्यंत':'Valid Until'}</small><strong>{device.license?.license?.valid_until||'—'}</strong></div><div><small>{mr?'डेटा फोल्डर':'Data Folder'}</small><strong style={{wordBreak:'break-all'}}>{device.data_dir}</strong></div></div>:<p>Loading…</p>}<p>{mr?'नवीन डिव्हाइस अधिकृत करण्यासाठी खालील विनंती कॉपी करा आणि License Authority Dashboard मध्ये पेस्ट करा. खाजगी signing key या शाळेच्या app मध्ये कधीही ठेवली जात नाही.':'For a new device, copy the authorization request and paste it into the separate License Authority Dashboard. The private signing key is never stored in the school application.'}</p><button onClick={copyActivationRequest}>{mr?'डिव्हाइस विनंती कॉपी करा':'Copy Device Authorization Request'}</button></section>}

 {tab==='masters'&&<section className="panel"><h3>{mr?'मानक साहित्य व मेनू पुनर्प्राप्त करा':'Restore Standard Ingredients & Menus'}</h3><p>{mr?'मूळ demo seed मधून 22 साहित्य आणि 12 साप्ताहिक मेनू पुन्हा आणले जातील. Demo शाळा किंवा demo users तयार होणार नाहीत. विद्यमान साठा, शाळा आणि व्यवहार हटवले जाणार नाहीत.':'Restores the original 22 ingredient masters and 12 weekly menu masters from the PM POSHAN demo seed. It does not recreate demo schools or demo users, and it does not delete existing stock, schools or transactions.'}</p><button disabled={busy} onClick={restoreMasters}>{mr?'मानक यादी पुनर्संचयित करा':'Restore Standard Master Lists'}</button></section>}
 </main>;
}
